language: elixir

matrix:
  include:
    - otp_release: 19.3
      elixir: 1.4
      env: RUST_TOOLCHAIN=stable
    - otp_release: 19.3
      elixir: 1.4
      env: RUST_TOOLCHAIN=nightly
    - otp_release: 20.3
      elixir: 1.5
      env: RUST_TOOLCHAIN=stable
    - otp_release: 20.3
      elixir: 1.5
      env: RUST_TOOLCHAIN=nightly
    - otp_release: 21.0
      elixir: 1.6
      env: RUST_TOOLCHAIN=stable
    - otp_release: 21.0
      elixir: 1.6
      env: RUST_TOOLCHAIN=nightly

env:
  global:
    - MIX_ENV=test

sudo: true

before_install:
  - curl https://static.rust-lang.org/rustup.sh | sh -s -- --default-toolchain $RUST_TOOLCHAIN

install:
  - mix local.rebar --force
  - mix local.hex --force

script:
  - cargo test
  - cd rustler_tests && mix test
